/*
 * Decompiled with CFR 0.152.
 */
package gnu.testlet.java.math.BigDecimal;

import gnu.testlet.TestHarness;
import gnu.testlet.Testlet;
import java.math.BigDecimal;
import java.math.MathContext;

public class divideToIntegralValue
implements Testlet {
    @Override
    public void test(TestHarness harness) {
        BigDecimal a;
        BigDecimal b = a = new BigDecimal("0");
        harness.checkPoint("basic tests");
        a = new BigDecimal("10");
        b = new BigDecimal("2");
        BigDecimal result = new BigDecimal("5");
        harness.check(a.divideToIntegralValue(b), result);
        a = a.negate();
        b = b.negate();
        result = new BigDecimal("5");
        harness.check(a.divideToIntegralValue(b), result);
        b = b.negate();
        result = new BigDecimal("-5");
        harness.check(a.divideToIntegralValue(b), result);
        harness.checkPoint("rounding to one");
        a = new BigDecimal("1000000000000000000");
        b = new BigDecimal("1000000000000000000");
        result = new BigDecimal("1");
        harness.check(a.divideToIntegralValue(b), result);
        a = a.negate();
        b = b.negate();
        result = new BigDecimal("1");
        harness.check(a.divideToIntegralValue(b), result);
        b = b.negate();
        result = new BigDecimal("-1");
        harness.check(a.divideToIntegralValue(b), result);
        harness.checkPoint("rounding to zero");
        a = new BigDecimal("10");
        b = new BigDecimal("20");
        result = new BigDecimal("0");
        harness.check(a.divideToIntegralValue(b), result);
        a = a.negate();
        b = b.negate();
        result = new BigDecimal("0");
        harness.check(a.divideToIntegralValue(b), result);
        b = b.negate();
        result = new BigDecimal("0");
        harness.check(a.divideToIntegralValue(b), result);
        harness.checkPoint("rounding after division");
        a = new BigDecimal("20.9");
        b = new BigDecimal("10.1");
        result = new BigDecimal("2");
        harness.check(a.divideToIntegralValue(b), result);
        a = a.negate();
        b = b.negate();
        result = new BigDecimal("2");
        harness.check(a.divideToIntegralValue(b), result);
        b = b.negate();
        result = new BigDecimal("-2");
        harness.check(a.divideToIntegralValue(b), result);
        harness.checkPoint("rounding after division");
        a = new BigDecimal("20.1");
        b = new BigDecimal("10.9");
        result = new BigDecimal("1");
        harness.check(a.divideToIntegralValue(b), result);
        a = a.negate();
        b = b.negate();
        result = new BigDecimal("1");
        harness.check(a.divideToIntegralValue(b), result);
        b = b.negate();
        result = new BigDecimal("-1");
        harness.check(a.divideToIntegralValue(b), result);
        harness.checkPoint("basic tests");
        a = new BigDecimal("10");
        b = new BigDecimal("2");
        result = new BigDecimal("5");
        harness.check(a.divideToIntegralValue(b, new MathContext(0)), result);
        a = a.negate();
        b = b.negate();
        result = new BigDecimal("5");
        harness.check(a.divideToIntegralValue(b, new MathContext(0)), result);
        b = b.negate();
        result = new BigDecimal("-5");
        harness.check(a.divideToIntegralValue(b, new MathContext(0)), result);
        harness.checkPoint("rounding to one");
        a = new BigDecimal("1000000000000000000");
        b = new BigDecimal("1000000000000000000");
        result = new BigDecimal("1");
        harness.check(a.divideToIntegralValue(b, new MathContext(0)), result);
        a = a.negate();
        b = b.negate();
        result = new BigDecimal("1");
        harness.check(a.divideToIntegralValue(b, new MathContext(0)), result);
        b = b.negate();
        result = new BigDecimal("-1");
        harness.check(a.divideToIntegralValue(b, new MathContext(0)), result);
        harness.checkPoint("rounding to zero");
        a = new BigDecimal("10");
        b = new BigDecimal("20");
        result = new BigDecimal("0");
        harness.check(a.divideToIntegralValue(b, new MathContext(0)), result);
        a = a.negate();
        b = b.negate();
        result = new BigDecimal("0");
        harness.check(a.divideToIntegralValue(b, new MathContext(0)), result);
        b = b.negate();
        result = new BigDecimal("0");
        harness.check(a.divideToIntegralValue(b, new MathContext(0)), result);
        harness.checkPoint("rounding after division");
        a = new BigDecimal("20.9");
        b = new BigDecimal("10.1");
        result = new BigDecimal("2");
        harness.check(a.divideToIntegralValue(b, new MathContext(0)), result);
        a = a.negate();
        b = b.negate();
        result = new BigDecimal("2");
        harness.check(a.divideToIntegralValue(b, new MathContext(0)), result);
        b = b.negate();
        result = new BigDecimal("-2");
        harness.check(a.divideToIntegralValue(b, new MathContext(0)), result);
        harness.checkPoint("rounding after division");
        a = new BigDecimal("20.1");
        b = new BigDecimal("10.9");
        result = new BigDecimal("1");
        harness.check(a.divideToIntegralValue(b, new MathContext(0)), result);
        a = a.negate();
        b = b.negate();
        result = new BigDecimal("1");
        harness.check(a.divideToIntegralValue(b, new MathContext(0)), result);
        b = b.negate();
        result = new BigDecimal("-1");
        harness.check(a.divideToIntegralValue(b, new MathContext(0)), result);
    }
}

