/*
 * Decompiled with CFR 0.152.
 */
package gnu.testlet.java.awt;

import gnu.testlet.TestHarness;
import gnu.testlet.Testlet;
import java.awt.CheckboxMenuItem;
import java.awt.Choice;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.List;
import java.awt.Menu;
import java.awt.MenuBar;
import java.awt.MenuItem;
import java.awt.PopupMenu;
import java.awt.ScrollPane;
import java.awt.TextField;

public class testName
implements Testlet {
    @Override
    public void test(TestHarness harness) {
        Choice a0 = new Choice();
        Choice a1 = new Choice();
        Choice a2 = new Choice();
        harness.check(a0.getName(), (Object)"choice0");
        harness.check(a1.getName(), (Object)"choice1");
        harness.check(a2.getName(), (Object)"choice2");
        Choice a3 = new Choice();
        Choice a4 = new Choice();
        Choice a5 = new Choice();
        harness.check(a5.getName(), (Object)"choice3");
        harness.check(a4.getName(), (Object)"choice4");
        harness.check(a3.getName(), (Object)"choice5");
        CheckboxMenuItem b0 = new CheckboxMenuItem();
        CheckboxMenuItem b1 = new CheckboxMenuItem();
        CheckboxMenuItem b2 = new CheckboxMenuItem();
        harness.check(b0.getName(), (Object)"chkmenuitem0");
        harness.check(b1.getName(), (Object)"chkmenuitem1");
        harness.check(b2.getName(), (Object)"chkmenuitem2");
        CheckboxMenuItem b5 = new CheckboxMenuItem();
        CheckboxMenuItem b4 = new CheckboxMenuItem();
        CheckboxMenuItem b3 = new CheckboxMenuItem();
        harness.check(b5.getName(), (Object)"chkmenuitem3");
        harness.check(b4.getName(), (Object)"chkmenuitem4");
        harness.check(b3.getName(), (Object)"chkmenuitem5");
        List c0 = new List();
        List c1 = new List();
        List c2 = new List();
        harness.check(c0.getName(), (Object)"list0");
        harness.check(c1.getName(), (Object)"list1");
        harness.check(c2.getName(), (Object)"list2");
        List c3 = new List();
        List c4 = new List();
        List c5 = new List();
        harness.check(c5.getName(), (Object)"list3");
        harness.check(c4.getName(), (Object)"list4");
        harness.check(c3.getName(), (Object)"list5");
        MenuBar d0 = new MenuBar();
        MenuBar d1 = new MenuBar();
        MenuBar d2 = new MenuBar();
        harness.check(d0.getName(), (Object)"menubar0");
        harness.check(d1.getName(), (Object)"menubar1");
        harness.check(d2.getName(), (Object)"menubar2");
        MenuBar d3 = new MenuBar();
        MenuBar d4 = new MenuBar();
        MenuBar d5 = new MenuBar();
        harness.check(d5.getName(), (Object)"menubar3");
        harness.check(d4.getName(), (Object)"menubar4");
        harness.check(d3.getName(), (Object)"menubar5");
        MenuItem e0 = new MenuItem();
        MenuItem e1 = new MenuItem();
        MenuItem e2 = new MenuItem();
        harness.check(e0.getName(), (Object)"menuitem0");
        harness.check(e1.getName(), (Object)"menuitem1");
        harness.check(e2.getName(), (Object)"menuitem2");
        MenuItem e3 = new MenuItem();
        MenuItem e4 = new MenuItem();
        MenuItem e5 = new MenuItem();
        harness.check(e5.getName(), (Object)"menuitem3");
        harness.check(e4.getName(), (Object)"menuitem4");
        harness.check(e3.getName(), (Object)"menuitem5");
        Menu f0 = new Menu();
        Menu f1 = new Menu();
        Menu f2 = new Menu();
        harness.check(f0.getName(), (Object)"menu0");
        harness.check(f1.getName(), (Object)"menu1");
        harness.check(f2.getName(), (Object)"menu2");
        Menu f3 = new Menu();
        Menu f4 = new Menu();
        Menu f5 = new Menu();
        harness.check(f5.getName(), (Object)"menu3");
        harness.check(f4.getName(), (Object)"menu4");
        harness.check(f3.getName(), (Object)"menu5");
        PopupMenu g0 = new PopupMenu();
        PopupMenu g1 = new PopupMenu();
        PopupMenu g2 = new PopupMenu();
        harness.check(g0.getName(), (Object)"popup0");
        harness.check(g1.getName(), (Object)"popup1");
        harness.check(g2.getName(), (Object)"popup2");
        PopupMenu g3 = new PopupMenu();
        PopupMenu g4 = new PopupMenu();
        PopupMenu g5 = new PopupMenu();
        harness.check(g5.getName(), (Object)"popup3");
        harness.check(g4.getName(), (Object)"popup4");
        harness.check(g3.getName(), (Object)"popup5");
        ScrollPane h0 = new ScrollPane();
        ScrollPane h1 = new ScrollPane();
        ScrollPane h2 = new ScrollPane();
        harness.check(h0.getName(), (Object)"scrollpane0");
        harness.check(h1.getName(), (Object)"scrollpane1");
        harness.check(h2.getName(), (Object)"scrollpane2");
        ScrollPane h3 = new ScrollPane();
        ScrollPane h4 = new ScrollPane();
        ScrollPane h5 = new ScrollPane();
        harness.check(h5.getName(), (Object)"scrollpane3");
        harness.check(h4.getName(), (Object)"scrollpane4");
        harness.check(h3.getName(), (Object)"scrollpane5");
        TextField i0 = new TextField();
        TextField i1 = new TextField();
        TextField i2 = new TextField();
        harness.check(i0.getName(), (Object)"textfield0");
        harness.check(i1.getName(), (Object)"textfield1");
        harness.check(i2.getName(), (Object)"textfield2");
        TextField i3 = new TextField();
        TextField i4 = new TextField();
        TextField i5 = new TextField();
        harness.check(i5.getName(), (Object)"textfield3");
        harness.check(i4.getName(), (Object)"textfield4");
        harness.check(i3.getName(), (Object)"textfield5");
        harness.check(new Cursor(0).getName(), (Object)"Default Cursor");
        harness.check(new Cursor(1).getName(), (Object)"Crosshair Cursor");
        harness.check(new Cursor(2).getName(), (Object)"Text Cursor");
        harness.check(new Cursor(3).getName(), (Object)"Wait Cursor");
        harness.check(new Cursor(4).getName(), (Object)"Southwest Resize Cursor");
        harness.check(new Cursor(5).getName(), (Object)"Southeast Resize Cursor");
        harness.check(new Cursor(6).getName(), (Object)"Northwest Resize Cursor");
        harness.check(new Cursor(7).getName(), (Object)"Northeast Resize Cursor");
        harness.check(new Cursor(8).getName(), (Object)"North Resize Cursor");
        harness.check(new Cursor(9).getName(), (Object)"South Resize Cursor");
        harness.check(new Cursor(10).getName(), (Object)"West Resize Cursor");
        harness.check(new Cursor(11).getName(), (Object)"East Resize Cursor");
        harness.check(new Cursor(12).getName(), (Object)"Hand Cursor");
        harness.check(new Cursor(13).getName(), (Object)"Move Cursor");
        Font j = new Font(null, 0, 0);
        harness.check(j.getName(), (Object)"Default");
        harness.check(j.getFontName(), (Object)"Dialog.plain");
    }
}

